version: "3.8"
services:
  authapi:
    build:
      context: ./authapi
      dockerfile: Dockerfile
    image: debs21/mern-auth-api:1.0.0.RELEASE
    container_name: auth-authapi
    ports:
      - "3000:3000"
  authui:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: debs21/mern-auth-ui:1.0.0.RELEASE
    container_name: auth-authui
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
