version: "3.8"
services:
  authapi:
    build: ./authAPI
    image: debs21/node-auth-api:latest
    container_name: auth-authapi
    ports:
      - "3000:3000"
    env_file:
      - ./authAPI/.env
  authui:
    build: ./client
    image: debs21/node-auth-ui:latest
    container_name: auth-authui
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    stdin_open: true
    tty: true
